PATH="/home/developer/.shell/bin:$PATH"
export PATH

source /home/developer/.shell/bashrc
if ! git config --global user.name &> /dev/null; then
  source /home/developer/.config/init/git-setup.sh
fi

export NVS_HOME="$HOME/.nvs"

