PATH="/home/user/.shell/bin:$PATH"
export PATH

source /home/user/.shell/bashrc
if ! git config --global user.name &> /dev/null; then
  source /home/user/.config/init/git-setup.sh
fi

export NVS_HOME="$HOME/.nvs"

