set number
set relativenumber
set encoding=UTF-8
set linebreak

set tabstop=2
set shiftwidth=2
set expandtab

set ignorecase
set smartcase

set cursorline
set cursorcolumn
set colorcolumn=120

set foldmethod=syntax
set foldlevel=8

set noshowmode
set laststatus=2

set mouse=a

set hlsearch
filetype plugin indent on

" Set default directory for the swap files
set directory=$HOME/.local/share/nvim/site/swapfiles/

set guicursor=n-v-c:block,i-ci-ve:ver25,r-cr:hor20,o:hor50
  \,a:blinkwait700-blinkoff400-blinkon250-Cursor/lCursor
  \,sm:block-blinkwait175-blinkoff150-blinkon175
set termguicolors

set wildignore+=*.png
set wildignore+=*.jpg
set wildignore+=*/node_modules/**
set wildignore+=*/bin/**
set wildignore+=*/obj/**

" Fix for esc delay issues
set ttimeoutlen=0

" Custom Registers
" Convert SQL Column to C# property
let @s = "^Wdi]^Pa wdi]hPlD:s/numeric/decimal/e:s/bit/bool/e:s/nvarchar/string/e:s/varchar/string/e:s/float/double/e:s/datetime2/datetime/e:s/bigint/float/e:s/text/string/e:s/datetime/DateTime/eA { get; set; }Ipublic j"
" Merge SQL mapping and C# properties
let @c = "^d2Wf{hDIbuilder.Property(pekbkbusuario => usuario.A)o.HasColumnName();hi\"\"mz}j^yi]dd`z^f\"\"0pj"
let @z = "\"zyiwb\"x y\"xyiwOprivate readonly \"xpa \"zpbi_A;/{%O\"zpI_A = \"zpA;=="

if exists('g:vscode') || exists('g:azuredatastudio')
  source $HOME/.modules/neovim-plug/vscode-plug.vimrc
else
  source $HOME/.modules/neovim-plug/plug.vimrc
endif

" Fix tag for targets (rollback to native NeoVim tags)
autocmd User targets#mappings#user call targets#mappings#extend({
    \ 't': {},
    \ })

" Custom Keymaps
"  Set space as the leader
let mapleader = " "

" NeoVim Custom keybindings
source $HOME/.local/share/nvim/site/nvim-keybindings.vimrc

"lua configuration
source $HOME/.local/share/nvim/site/setup.lua

" Yank highlight
autocmd TextYankPost * silent! lua vim.highlight.on_yank { higroup="TabLineSel", timeout=450 }

" Transparent floating windows
set winblend=15
set pumblend=15

let g:rainbow_conf = {
\	'separately': {
\		'*': {},
\		'html': 0
\	}
\}

" Rainbow brackets
let g:rainbow_active = 1

" vim-markdown Settings
let g:vim_markdown_folding_disabled = 1

" Write all buffers before navigating from Vim to tmux pane
let g:tmux_navigator_save_on_switch = 2

" " FZF configuration
" let g:fzf_layout = { 'window': { 'width': 0.85, 'height': 0.85 } }

" When running on Azure Data Studio (with neovim plugin)
if exists('g:azuredatastudio')
  source $HOME/.modules/vim/azuredatastudio-keybindings.vimrc

  " Yank highlight
  augroup highlight_yank
    autocmd!
    autocmd TextYankPost * silent! lua vim.highlight.on_yank { higroup="IncSearch", timeout=450 }
  augroup END

" When running on VS Code (with neovim plugin)
elseif exists('g:vscode')
  source $HOME/.modules/vim/vscode-keybindings.vimrc

  " Yank highlight
  augroup highlight_yank
    autocmd!
    autocmd TextYankPost * silent! lua vim.highlight.on_yank { higroup="IncSearch", timeout=450 }
  augroup END

else
" Colorscheme
syntax enable
  set background=dark
  let g:one_allow_italics = 1 " One colorscheme configuration
  let g:tokyonight_style = "storm" " Tokyo Night colorscheme configuration

  colorscheme tokyonight
  highlight Normal guibg=none
  highlight Inactive guibg=none
  highlight MsgArea guibg=#1a1b26
  highlight LineNr guibg=#1a1b26
  highlight CursorLineNr guibg=#1a1b26
  highlight Comment guifg=#819c98
  set fillchars+=vert:│
  highlight VertSplit guibg=none guifg=#414868

  " Filetype detections
  autocmd BufNewFile,BufRead *.code-snippets set filetype=json
  autocmd BufNewFile,BufRead *.tsx,*.jsx set filetype=typescript
  autocmd BufNewFile,BufRead *.config,*.csproj set filetype=xml

  " Copilot node_version
  let g:copilot_node_command = "$HOME/.nvs/copilot-node"
  let g:copilot_no_tab_map = v:true
endif

" Disable modelines for security reasons
set nomodeline
