nvim -n -u /home/developer/.modules/neovim-treesitter/treesitter-setup.vimrc +"TSInstallSync c" +qall
nvim -n -u /home/developer/.modules/neovim-treesitter/treesitter-setup.vimrc +"TSInstallSync c_sharp" +qall
nvim -n -u /home/developer/.modules/neovim-treesitter/treesitter-setup.vimrc +"TSInstallSync cpp" +qall
nvim -n -u /home/developer/.modules/neovim-treesitter/treesitter-setup.vimrc +"TSInstallSync css" +qall
nvim -n -u /home/developer/.modules/neovim-treesitter/treesitter-setup.vimrc +"TSInstallSync dockerfile" +qall
nvim -n -u /home/developer/.modules/neovim-treesitter/treesitter-setup.vimrc +"TSInstallSync html" +qall
nvim -n -u /home/developer/.modules/neovim-treesitter/treesitter-setup.vimrc +"TSInstallSync json" +qall
nvim -n -u /home/developer/.modules/neovim-treesitter/treesitter-setup.vimrc +"TSInstallSync lua" +qall
nvim -n -u /home/developer/.modules/neovim-treesitter/treesitter-setup.vimrc +"TSInstallSync regex" +qall
nvim -n -u /home/developer/.modules/neovim-treesitter/treesitter-setup.vimrc +"TSInstallSync rust" +qall
nvim -n -u /home/developer/.modules/neovim-treesitter/treesitter-setup.vimrc +"TSInstallSync typescript" +qall
nvim -n -u /home/developer/.modules/neovim-treesitter/treesitter-setup.vimrc +"TSInstallSync vim" +qall
nvim -n -u /home/developer/.modules/neovim-treesitter/treesitter-setup.vimrc +"TSInstallSync yaml" +qall
