name: Docker Build

on: [push]

env:
  CACHE_IMAGE: thomazmoura/dev-environment
  DOCKER_BUILDKIT: 1

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build from dockerfile
        run: |
          docker build \
            --cache-from $CACHE_IMAGE:latest \
            --tag $CACHE_IMAGE:latest \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            "."
      - name: Push to docker hub as latest
        if: ${{ github.ref.name == 'main' }}
        run: docker push $CACHE_IMAGE:latest
      - name: Push to docker hub as branch name
        if: ${{ github.ref.name != 'main' }}
        run: docker push $CACHE_IMAGE:${{ github.ref.name }}

