name: Docker Build

on: [push]

env:
  CACHE_IMAGE: thomazmoura/dev-environment
  DOCKER_BUILDKIT: 1

jobs:
  main-build:
    name: Build Main branch Docker Image
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' }}
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build base container from debian using base.Dockerfile
        run: |
          docker build \
            --cache-from $CACHE_IMAGE:base \
            --tag $CACHE_IMAGE:base \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --file base.Dockerfile \
            "."
      - name: Push to docker hub as latest
        run: docker push $CACHE_IMAGE:base

      - name: Build main container from base using Dockerfile
        run: |
          export DockerBase='thomazmoura/dev-environment:base' 
          docker build \
            --cache-from $CACHE_IMAGE:latest \
            --tag $CACHE_IMAGE:latest \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --file Dockerfile \
            "."
      - name: Push to docker hub as latest
        run: docker push $CACHE_IMAGE:latest

      - name: Build qmk-base from base using qmk-base.Dockerfile
        run: |
          docker build \
            --cache-from $CACHE_IMAGE:qmk_base \
            --tag $CACHE_IMAGE:qmk_base \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --file qmk-base.Dockerfile \
            "."
      - name: Push to docker hub as latest
        run: docker push $CACHE_IMAGE:qmk_base

      - name: Build QMK container from qmk-base using Dockerfile
        run: |
          export DockerBase='thomazmoura/dev-environment:qmk_base' 
          docker build \
            --cache-from $CACHE_IMAGE:qmk \
            --tag $CACHE_IMAGE:qmk \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --file Dockerfile \
            "."
      - name: Push to docker hub as latest
        run: docker push $CACHE_IMAGE:qmk

  alt-build:
    name: Build alternative branch Docker Image
    runs-on: ubuntu-latest
    if: ${{ github.ref_name != 'main' }}
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build from debian using base.Dockerfile
        run: |
          GIT_BRANCH=$(tr -s / _ <<< "$GITHUB_REF_NAME") &&
          docker build \
            --cache-from $CACHE_IMAGE:base_$GIT_BRANCH \
            --cache-from $CACHE_IMAGE:base \
            --tag $CACHE_IMAGE:base_$GIT_BRANCH \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --file base.Dockerfile
            "."
      - name: Push to docker hub as branch name (with '/' escaped as '_')
        run: |
          GIT_BRANCH=$(tr -s / _ <<< "$GITHUB_REF_NAME") &&
          docker image push $CACHE_IMAGE:base_$GIT_BRANCH

      - name: Build from base using Dockerfile
        run: |
          GIT_BRANCH=$(tr -s / _ <<< "$GITHUB_REF_NAME") &&
          export DockerBase='thomazmoura/dev-environment:base_$GIT_BRANCH' 
          docker build \
            --cache-from $CACHE_IMAGE:$GIT_BRANCH \
            --cache-from $CACHE_IMAGE:latest \
            --tag $CACHE_IMAGE:$GIT_BRANCH \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --file Dockerfile
            "."
      - name: Push to docker hub as branch name (with '/' escaped as '_')
        run: |
          GIT_BRANCH=$(tr -s / _ <<< "$GITHUB_REF_NAME") &&
          docker image push $CACHE_IMAGE:$GIT_BRANCH

      - name: Build from base_GIT_BRANCH using base.Dockerfile
        run: |
          GIT_BRANCH=$(tr -s / _ <<< "$GITHUB_REF_NAME") &&
          docker build \
            --cache-from $CACHE_IMAGE:qmk_base_$GIT_BRANCH \
            --cache-from $CACHE_IMAGE:qmk_base \
            --tag $CACHE_IMAGE:qmk_base_$GIT_BRANCH \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --file qmk-base.Dockerfile
            "."
      - name: Push to docker hub as branch name (with '/' escaped as '_')
        run: |
          GIT_BRANCH=$(tr -s / _ <<< "$GITHUB_REF_NAME") &&
          docker image push $CACHE_IMAGE:base_$GIT_BRANCH

      - name: Build from dockerfile with cache from branch
        run: |
          GIT_BRANCH=$(tr -s / _ <<< "$GITHUB_REF_NAME") &&
          export DockerBase='thomazmoura/dev-environment:qmk_base_$GIT_BRANCH' 
          docker build \
            --cache-from $CACHE_IMAGE:qmk_$GIT_BRANCH \
            --cache-from $CACHE_IMAGE:qmk \
            --tag $CACHE_IMAGE:qmk_$GIT_BRANCH \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --file Dockerfile
            "."
      - name: Push to docker hub as branch name (with '/' escaped as '_')
        run: |
          GIT_BRANCH=$(tr -s / _ <<< "$GITHUB_REF_NAME") &&
          docker image push $CACHE_IMAGE:qmk_$GIT_BRANCH

