name: Docker Build

on: [push]

env:
  CACHE_IMAGE: thomazmoura/dev-environment
  DOCKER_BUILDKIT: 1

jobs:
  main-build:
    name: Build Main Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Steps to be run for main branch
      - name: Build from dockerfile with cache from latest
        if: ${{ github.ref_name == 'main' }}
        run: |
          docker build \
            --cache-from $CACHE_IMAGE:latest \
            --tag $CACHE_IMAGE:latest \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            "."
      - name: Push to docker hub as latest
        if: ${{ github.ref_name == 'main' }}
        run: docker push $CACHE_IMAGE:latest

      # Steps to be run for feature and fix branches
      - name: Build from dockerfile with cache from branch
        if: ${{ github.ref_name != 'main' }}
        run: |
          GIT_BRANCH=$(tr -s / _ <<< "$GITHUB_REF_NAME") &&
          docker build \
            --cache-from $CACHE_IMAGE:$GIT_BRANCH \
            --cache-from $CACHE_IMAGE:latest \
            --tag $CACHE_IMAGE:$GIT_BRANCH \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            "."
      - name: Push to docker hub as branch name (with '/' escaped as '_')
        if: ${{ github.ref_name != 'main' }}
        run: |
          GIT_BRANCH=$(tr -s / _ <<< "$GITHUB_REF_NAME") &&
          docker image push $CACHE_IMAGE:$GIT_BRANCH

  qmk-build:
    name: Build QMK Docker Image
    needs: main-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Steps to be run for main branch
      - name: Build from dockerfile with cache from latest
        if: ${{ github.ref_name == 'main' }}
        run: |
          cd ./alt/qmk
          docker build \
            --cache-from $CACHE_IMAGE:qmk \
            --tag $CACHE_IMAGE:qmk \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            "."
      - name: Push to docker hub as latest
        if: ${{ github.ref_name == 'main' }}
        run: docker push $CACHE_IMAGE:qmk

      # Steps to be run for feature and fix branches
      - name: Build from dockerfile with cache from branch
        if: ${{ github.ref_name != 'main' }}
        run: |
          GIT_BRANCH=$(tr -s / _ <<< "$GITHUB_REF_NAME") &&
          docker build \
            --cache-from $CACHE_IMAGE:qmk_$GIT_BRANCH \
            --cache-from $CACHE_IMAGE:qmk \
            --tag $CACHE_IMAGE:qmk_$GIT_BRANCH \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            "."
      - name: Push to docker hub as branch name (with '/' escaped as '_')
        if: ${{ github.ref_name != 'main' }}
        run: |
          GIT_BRANCH=$(tr -s / _ <<< "$GITHUB_REF_NAME") &&
          docker image push $CACHE_IMAGE:qmk_$GIT_BRANCH

